[tool.poetry]
name = "hippunfold"
version = "1.5.2-pre.2"
description = "BIDS App for Hippocampal AutoTop (automated hippocampal unfolding and subfield segmentation)"
readme = "README.md"
license = "MIT"
authors = ["Jordan DeKraker & Ali Khan <alik@robarts.ca>"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
snakemake = [
    { version=">=7.20,<8", python = "<3.11" },
    { version=">=8.1.2", python = ">=3.11" },
]
snakebids = "0.14.0"
appdirs = "^1.4.4"
Jinja2 = "^3.0.3"
pygraphviz = "1.7"
Pygments = "^2.10.0"
pulp = { version="<2.8.0", python = "<3.11" }
pandas = [
    { version = "<=2.0.3", python = "<3.9" },
    { version = ">=2.1.1", python = ">=3.12" },
]
nibabel = "^5.3.2"
pyvista = "^0.44.2"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
pytest-console-scripts = "^1.2.1"
pytest = "^6.2.5"
black = ">=22.1.0,<23.0.0"
pylint = "^2.11.1"
isort = "^5.10.1"
poethepoet = "^0.10.0"
snakefmt = ">=0.5.0"
[tool.poetry.scripts]
hippunfold = "hippunfold.run:app.run"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
[tool.poe.tasks]
quality_check = { shell = "isort hippunfold/*.py -c && black hippunfold --check && snakefmt hippunfold --check" }
quality_fix = { shell = "isort hippunfold/*.py && black hippunfold  && snakefmt hippunfold" }

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pylint.master]
ignore-patterns = "^[0-9][0-9]+_,^test_"

[tool.pylint.format]
good-names = "i,j,k,ex,_,x,y,f,d"

[tool.pylint.messages_control]
disable = """
    missing-function-docstring,
    missing-module-docstring,
    fixme
"""
